@startuml
class EventReward {
    + <<override>> AreEventsConditionMet(world:World, champion:Champion) : bool
    + <<override>> DoEvent(logic:WorldLogic, champion:Champion) : void
    + {static} <<new>> Get(id:string) : EventState
}
EventData <|-- EventReward
EventReward --> "rarity" RarityData
@enduml
