@startuml
!include .\\AvatarPanel.puml
!include .\\CardLine.puml
!include .\\CardZoomPanel.puml
!include .\\LanPanel.puml
!include .\\LoadPanel.puml
!include .\\LoadUI.puml
!include .\\LobbyCreatePanel.puml
!include .\\LobbyLine.puml
!include .\\LobbyPanel.puml
!include .\\LobbyRoomPanel.puml
!include .\\LoginMenu.puml
!include .\\MainMenu.puml
!include .\\MenuLoadPanel.puml
!include .\\PlayerLine.puml
@enduml
