@startuml
class LobbyLine {
    + SetLine(room:LobbyGame) : void
    + SetSelected(selected:bool) : void
    + OnClick() : void
    + GetGame() : LobbyGame
}
MonoBehaviour <|-- LobbyLine
LobbyLine --> "title" Text
LobbyLine --> "subtitle" Text
LobbyLine --> "players" Text
LobbyLine --> "highlight" Image
@enduml
