@startuml
class EffectUpgradeCard {
    + <<override>> DoEffect(logic:BattleLogic, ability:AbilityData, caster:BattleCharacter, card:Card, target:Card) : void
}
EffectData <|-- EffectUpgradeCard
@enduml
