@startuml
class EffectRemoveItem {
    + <<override>> DoMapEventEffect(logic:WorldLogic, evt:EventEffect, champion:Champion) : void
}
EffectData <|-- EffectRemoveItem
EffectRemoveItem --> "item" CardData
@enduml
