@startuml
class EffectRedrawHand {
    + <<override>> DoEffect(logic:BattleLogic, ability:AbilityData, caster:BattleCharacter, card:Card, target:BattleCharacter) : void
}
EffectData <|-- EffectRedrawHand
@enduml
