@startuml
!include .\\EffectAddAbility.puml
!include .\\EffectAddStat.puml
!include .\\EffectAddStatCount.puml
!include .\\EffectAddStatDelayed.puml
!include .\\EffectAddStatRoll.puml
!include .\\EffectAddTrait.puml
!include .\\EffectClearStatus.puml
!include .\\EffectClearTemp.puml
!include .\\EffectConsume.puml
!include .\\EffectCreate.puml
!include .\\EffectDamage.puml
!include .\\EffectDamageHalf.puml
!include .\\EffectDamageRandom.puml
!include .\\EffectDestroy.puml
!include .\\EffectDiscard.puml
!include .\\EffectDraw.puml
!include .\\EffectGainCard.puml
!include .\\EffectGainItem.puml
!include .\\EffectGainMana.puml
!include .\\EffectHeal.puml
!include .\\EffectMapOngoingBoost.puml
!include .\\EffectMultStat.puml
!include .\\EffectPlay.puml
!include .\\EffectRedrawHand.puml
!include .\\EffectRemoveAbility.puml
!include .\\EffectRemoveCard.puml
!include .\\EffectRemoveItem.puml
!include .\\EffectRemoveStatus.puml
!include .\\EffectRemoveTrait.puml
!include .\\EffectRepeat.puml
!include .\\EffectResetStat.puml
!include .\\EffectResurrect.puml
!include .\\EffectRoll.puml
!include .\\EffectSelectedValue.puml
!include .\\EffectSendPile.puml
!include .\\EffectSetStat.puml
!include .\\EffectSetTarget.puml
!include .\\EffectSetTrait.puml
!include .\\EffectShuffle.puml
!include .\\EffectSummonCard.puml
!include .\\EffectSummonCharacter.puml
!include .\\EffectTransformCard.puml
!include .\\EffectTransformCharacter.puml
!include .\\EffectUpgradeCard.puml
@enduml
