@startuml
class GameAction <<static>> {
    + <<const>> None : ushort = 0
    + <<const>> NewScenario : ushort = 100
    + <<const>> LoadScenario : ushort = 110
    + <<const>> CreateChampion : ushort = 120
    + <<const>> DeleteChampion : ushort = 122
    + <<const>> SendUserData : ushort = 130
    + <<const>> StartGame : ushort = 150
    + <<const>> StartTest : ushort = 155
    + <<const>> ChangeState : ushort = 160
    + <<const>> Connected : ushort = 200
    + <<const>> PlayerConnected : ushort = 202
    + <<const>> PlayerDisconnected : ushort = 204
    + <<const>> ServerMessage : ushort = 220
    + <<const>> RefreshWorld : ushort = 250
    + <<const>> RefreshBattle : ushort = 260
    + <<const>> MapMove : ushort = 300
    + <<const>> MapEventDone : ushort = 310
    + <<const>> MapEventDoneChampion : ushort = 311
    + <<const>> MapEventChoice : ushort = 320
    + <<const>> MapRewardCardChoice : ushort = 322
    + <<const>> MapRewardItemChoice : ushort = 323
    + <<const>> MapUpgradeCard : ushort = 324
    + <<const>> MapLevelUp : ushort = 326
    + <<const>> MapTrashCard : ushort = 328
    + <<const>> ShopBuyCard : ushort = 340
    + <<const>> ShopSellCard : ushort = 341
    + <<const>> ShopBuyItem : ushort = 342
    + <<const>> ShopSellItem : ushort = 343
    + <<const>> GainChampion : ushort = 350
    + <<const>> RemoveChampion : ushort = 352
    + <<const>> GainAlly : ushort = 354
    + <<const>> RemoveAlly : ushort = 356
    + <<const>> GameStarted : ushort = 500
    + <<const>> GameEnded : ushort = 502
    + <<const>> GameTest : ushort = 504
    + <<const>> MapMoved : ushort = 510
    + <<const>> MapEventStarted : ushort = 520
    + <<const>> MapRewardSelected : ushort = 530
    + <<const>> MapChoiceSelected : ushort = 532
    + <<const>> MapCardUpgraded : ushort = 540
    + <<const>> MapCardBought : ushort = 542
    + <<const>> MapItemBought : ushort = 543
    + <<const>> PlayCard : ushort = 1000
    + <<const>> Attack : ushort = 1010
    + <<const>> AttackPlayer : ushort = 1012
    + <<const>> Move : ushort = 1015
    + <<const>> CastAbility : ushort = 1020
    + <<const>> UseItem : ushort = 1025
    + <<const>> SelectCard : ushort = 1030
    + <<const>> SelectCharacter : ushort = 1032
    + <<const>> SelectSlot : ushort = 1034
    + <<const>> SelectChoice : ushort = 1036
    + <<const>> SelectCost : ushort = 1037
    + <<const>> CancelSelect : ushort = 1039
    + <<const>> EndTurn : ushort = 1040
    + <<const>> Resign : ushort = 1050
    + <<const>> ChatMessage : ushort = 1090
    + <<const>> BattleStarted : ushort = 2010
    + <<const>> BattleEnded : ushort = 2012
    + <<const>> NewTurn : ushort = 2015
    + <<const>> CardPlayed : ushort = 2020
    + <<const>> CardSummoned : ushort = 2022
    + <<const>> CardTransformed : ushort = 2023
    + <<const>> CardDiscarded : ushort = 2025
    + <<const>> CardDrawn : ushort = 2026
    + <<const>> CharacterMoved : ushort = 2030
    + <<const>> CharacterDamaged : ushort = 2032
    + <<const>> ItemUsed : ushort = 2035
    + <<const>> AbilityTrigger : ushort = 2040
    + <<const>> AbilityTargetCard : ushort = 2042
    + <<const>> AbilityTargetCharacter : ushort = 2043
    + <<const>> AbilityTargetSlot : ushort = 2044
    + <<const>> AbilityEnd : ushort = 2048
    + <<const>> SecretTriggered : ushort = 2060
    + <<const>> SecretResolved : ushort = 2061
    + <<const>> ValueRolled : ushort = 2070
    + {static} GetString(type:ushort) : string
}
@enduml
