@startuml
class TimeToolMono {
    + StartRoutine(routine:IEnumerator) : Coroutine
    + StopRoutine(routine:Coroutine) : void
}
MonoBehaviour <|-- TimeToolMono
TimeToolMono --> "Inst" TimeToolMono
@enduml
