@startuml
class ConditionCardPile {
    + <<override>> IsTargetConditionMet(data:Battle, ability:AbilityData, caster:BattleCharacter, card:Card, target:Card) : bool
    + <<override>> IsTargetConditionMet(data:Battle, ability:AbilityData, caster:BattleCharacter, card:Card, target:BattleCharacter) : bool
    + <<override>> IsTargetConditionMet(data:Battle, ability:AbilityData, caster:BattleCharacter, card:Card, target:Slot) : bool
}
ConditionData <|-- ConditionCardPile
ConditionCardPile --> "type" PileType
ConditionCardPile --> "oper" ConditionOperatorBool
@enduml
