@startuml
class ConditionCharacterFront {
    + <<override>> IsTargetConditionMet(data:Battle, ability:AbilityData, caster:BattleCharacter, card:Card, target:BattleCharacter) : bool
}
ConditionData <|-- ConditionCharacterFront
ConditionCharacterFront --> "oper" ConditionOperatorBool
@enduml
